---
title: Open Ownership
timezone: UTC
collections:
  authors:
    title: Authors
    output: false
  guide:
    title: Guide
    output: true
  inmedia:
    title: In the Media
    output: false
  posts:
    title: Posts
    output: true
  principles:
    title: Principles for Effective Beneficial Ownership Disclosure
    output: true
    sort_by: order
  resources:
    title: Resources
    output: false
  team:
    title: Team
    output: true
  uploads:
    title: Uploads
    output: true
  visualisation:
    title: Visualisation System (BOVS)
    output: true
  what-we-do:
    title: What We Do
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image: 
    description: 
    author: 
    is_featured: false
    layout: post
    permalink: "/:categories/:title/"
- scope:
    path: ''
    type: pages
  values:
    description: 
    layout: page
- scope:
    path: ''
    type: resources
  values:
    description: 
    files:
      en: 
    author: 
    thumbnail-image: 
    thumbnail-image-class: 
    resource_type: 
    is_featured: false
    position: 
- scope:
    path: ''
    type: principles
  values:
    job-title: 
    image: 
    email: 
    social: 
    layout: principles
- scope:
    path: ''
    type: team
  values:
    job-title: 
    image: 
    email: 
    social: 
    layout: team
- scope:
    path: ''
    type: visualisation
  values:
    layout: visualisation
url: https://www.openownership.org
description: Driving the global shift towards transparency over who owns and controls
  companies.
permalink: pretty
include:
- _redirects
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
- assets/js/app.js
plugins:
- jekyll-paginate-v2
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  auto_ids: true
  auto_id_stripping: true
  transliterated_header_ids: true
  auto_id_prefix: section-
  toc_levels: 1..3
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
highlighter: rouge
colophon: http://www.garethjohnsdesign.com
company: Open Ownership
email: info@openownership.org
tag_manager: GTM-KHKK838
logo: "/assets/img/logo.svg"
placeholder: "/assets/img/placeholder.jpg"
per_page: 12
date_format: "%b %Y"
future: true
social:
  twitter: https://twitter.com/openownership
  medium: https://medium.com/beneficial-ownership
  github: https://github.com/openownership
guides:
  consider: "/guide/consider"
  commit: "/guide/commit"
  legal: "/guide/legal"
  systems: "/guide/systems"
  data: "/guide/data"
  publish: "/guide/publish"
pagination:
  enabled: true
  per_page: 6
  limit: 0
  permalink: "/:num/"
  title: ":title — :num of :max"
  sort_field: date
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    slugify:
      mode: raw
      cased: true
    layouts:
    - tags.html
    title: Posts tagged with :tag
    permalink: "/tag/:tag"
imgix:
  source: open-ownership-team.imgix.net
disable_disk_cache: true
